`include "../common/can_defs.vh"

// =============================================================================
// Module : reg_bank
// -----------------------------------------------------------------------------
// Register storage and byte-wide SPI access for the reduced CAN controller.
// Control decisions (TXREQ sequencing, interrupt routing, error-state handling,
// status-byte assembly) are intentionally owned by control_logic.
// =============================================================================

module reg_bank (
    input  wire        clk,
    input  wire        rst_n,

    // SPI register bus
    input  wire [7:0]  addr,
    input  wire [7:0]  wdata,
    input  wire        we,
    output reg  [7:0]  rdata,

    // Reset and hardware events generated by Control Logic
    input  wire        control_reset,
    input  wire        txreq_set,
    input  wire        txreq_clear,
    input  wire        set_rx0if,
    input  wire        clear_rx0if,
    input  wire        set_tx0if,
    input  wire        clear_tx0if,
    input  wire        set_merrf,
    input  wire        clear_merrf,
    input  wire        set_errif,

    // Error-counter values monitored by Control Logic
    input  wire [7:0]  tec_in,
    input  wire [7:0]  rec_in,

    // Register values consumed by Control Logic
    output reg  [7:0]  canctrl,
    output reg  [7:0]  bfpctrl,
    output reg  [7:0]  caninte,
    output reg  [7:0]  canintf,

    // Fixed operating-mode visibility
    output wire [2:0]  opmod,
    output wire        config_mode,
    output wire        normal_mode,

    // TX Buffer 0 host-side staging registers
    output reg  [10:0] txb0_id,
    output reg  [63:0] txb0_data,
    output reg  [3:0]  txb0_dlc,
    output reg         txb0_rtr,
    output reg         txb0_txreq,
    output reg         txb0_wr,

    // RX Buffer 0 contents for host reads
    input  wire [10:0] rxb0_id,
    input  wire [63:0] rxb0_data,
    input  wire [3:0]  rxb0_dlc,
    input  wire        rxb0_rtr,

    // Hardcoded filter/mask configuration
    output wire [10:0] rxm0_mask,
    output wire [10:0] rxf0_id
);

    // -------------------------------------------------------------------------
    // Register address map - reduced MCP2515-compatible subset
    // -------------------------------------------------------------------------
    localparam [7:0] ADDR_RXF0SIDH = 8'h00;
    localparam [7:0] ADDR_RXF0SIDL = 8'h01;
    localparam [7:0] ADDR_BFPCTRL  = 8'h0C;
    localparam [7:0] ADDR_CANSTAT  = 8'h0E;
    localparam [7:0] ADDR_CANCTRL  = 8'h0F;
    localparam [7:0] ADDR_TEC      = 8'h1C;
    localparam [7:0] ADDR_REC      = 8'h1D;
    localparam [7:0] ADDR_RXM0SIDH = 8'h20;
    localparam [7:0] ADDR_RXM0SIDL = 8'h21;
    localparam [7:0] ADDR_CANINTE  = 8'h2B;
    localparam [7:0] ADDR_CANINTF  = 8'h2C;

    localparam [7:0] ADDR_TXB0CTRL = 8'h30;
    localparam [7:0] ADDR_TXB0SIDH = 8'h31;
    localparam [7:0] ADDR_TXB0SIDL = 8'h32;
    localparam [7:0] ADDR_TXB0DLC  = 8'h35;
    localparam [7:0] ADDR_TXB0D0   = 8'h36;
    localparam [7:0] ADDR_TXB0D1   = 8'h37;
    localparam [7:0] ADDR_TXB0D2   = 8'h38;
    localparam [7:0] ADDR_TXB0D3   = 8'h39;
    localparam [7:0] ADDR_TXB0D4   = 8'h3A;
    localparam [7:0] ADDR_TXB0D5   = 8'h3B;
    localparam [7:0] ADDR_TXB0D6   = 8'h3C;
    localparam [7:0] ADDR_TXB0D7   = 8'h3D;

    localparam [7:0] ADDR_RXB0CTRL = 8'h60;
    localparam [7:0] ADDR_RXB0SIDH = 8'h61;
    localparam [7:0] ADDR_RXB0SIDL = 8'h62;
    localparam [7:0] ADDR_RXB0DLC  = 8'h65;
    localparam [7:0] ADDR_RXB0D0   = 8'h66;
    localparam [7:0] ADDR_RXB0D1   = 8'h67;
    localparam [7:0] ADDR_RXB0D2   = 8'h68;
    localparam [7:0] ADDR_RXB0D3   = 8'h69;
    localparam [7:0] ADDR_RXB0D4   = 8'h6A;
    localparam [7:0] ADDR_RXB0D5   = 8'h6B;
    localparam [7:0] ADDR_RXB0D6   = 8'h6C;
    localparam [7:0] ADDR_RXB0D7   = 8'h6D;

    // Only the interrupt sources present in the reduced design are retained.
    localparam [7:0] SUPPORTED_INT_MASK = 8'b1010_0101; // MERRF, ERRIF, TX0IF, RX0IF

    // SOW fixes the controller in Normal mode.
    assign opmod       = 3'b000;
    assign config_mode = 1'b0;
    assign normal_mode = 1'b1;

    // Filter and mask writes are out of scope. Keep the existing project
    // power-up values immutable: filter ID 0 with all 11 ID bits compared.
    assign rxm0_mask = 11'h7FF;
    assign rxf0_id   = 11'h000;

    // TEC/REC are stored as register-bank snapshots. Their behavior is owned by
    // the error-management/control path, not recomputed here.
    reg [7:0] tec_reg;
    reg [7:0] rec_reg;

    // CANSTAT interrupt code. Unsupported sources can never appear in CANINTF.
    reg [2:0] icod;
    always @(*) begin
        if (canintf[7] || canintf[5])
            icod = 3'b001; // Error / message error
        else if (canintf[2])
            icod = 3'b011; // TXB0
        else if (canintf[0])
            icod = 3'b110; // RXB0
        else
            icod = 3'b000; // No pending interrupt
    end

    // -------------------------------------------------------------------------
    // Register storage and host writes
    // -------------------------------------------------------------------------
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            canctrl    <= 8'h00;
            bfpctrl    <= 8'h00;
            caninte    <= 8'h00;
            canintf    <= 8'h00;
            tec_reg    <= 8'h00;
            rec_reg    <= 8'h00;

            txb0_id    <= 11'h000;
            txb0_data  <= 64'h0000_0000_0000_0000;
            txb0_dlc   <= 4'd0;
            txb0_rtr   <= 1'b0;
            txb0_txreq <= 1'b0;
            txb0_wr    <= 1'b0;
        end else if (control_reset) begin
            canctrl    <= 8'h00;
            bfpctrl    <= 8'h00;
            caninte    <= 8'h00;
            canintf    <= 8'h00;
            tec_reg    <= 8'h00;
            rec_reg    <= 8'h00;

            txb0_id    <= 11'h000;
            txb0_data  <= 64'h0000_0000_0000_0000;
            txb0_dlc   <= 4'd0;
            txb0_rtr   <= 1'b0;
            txb0_txreq <= 1'b0;
            txb0_wr    <= 1'b0;
        end else begin
            // Registered mirror of the error counters supplied by Control Logic.
            tec_reg <= tec_in;
            rec_reg <= rec_in;

            // Default: no TX-buffer commit pulse. The pulse is intentionally
            // registered so the TX buffer samples already-updated staging data.
            txb0_wr <= 1'b0;

            // Host-writable register fields.
            if (we) begin
                case (addr)
                    ADDR_CANCTRL: begin
                        // REQOP is locked to Normal mode. Lower fields are kept
                        // only as inert register storage; no omitted mode is enabled.
                        canctrl <= {3'b000, wdata[4:0]};
                    end

                    ADDR_BFPCTRL: begin
                        // Register exists per SOW; physical RXnBF pins are removed.
                        bfpctrl <= wdata;
                    end

                    ADDR_CANINTE: begin
                        caninte <= wdata & SUPPORTED_INT_MASK;
                    end

                    ADDR_CANINTF: begin
                        // Host clearing is write-zero-to-clear. Hardware SET events
                        // below have priority if a new event arrives simultaneously.
                        canintf <= canintf & (wdata & SUPPORTED_INT_MASK);
                    end

                    // TXB0 message staging. TXREQ itself is not controlled here;
                    // Control Logic owns the TXREQ state machine.
                    ADDR_TXB0SIDH: begin
                        txb0_id[10:3] <= wdata;
                        txb0_wr       <= 1'b1;
                    end
                    ADDR_TXB0SIDL: begin
                        txb0_id[2:0] <= wdata[7:5];
                        txb0_wr      <= 1'b1;
                    end
                    ADDR_TXB0DLC: begin
                        txb0_rtr <= wdata[6];
                        txb0_dlc <= (wdata[3:0] > 4'd8) ? 4'd8 : wdata[3:0];
                        txb0_wr  <= 1'b1;
                    end
                    ADDR_TXB0D0: begin txb0_data[7:0]   <= wdata; txb0_wr <= 1'b1; end
                    ADDR_TXB0D1: begin txb0_data[15:8]  <= wdata; txb0_wr <= 1'b1; end
                    ADDR_TXB0D2: begin txb0_data[23:16] <= wdata; txb0_wr <= 1'b1; end
                    ADDR_TXB0D3: begin txb0_data[31:24] <= wdata; txb0_wr <= 1'b1; end
                    ADDR_TXB0D4: begin txb0_data[39:32] <= wdata; txb0_wr <= 1'b1; end
                    ADDR_TXB0D5: begin txb0_data[47:40] <= wdata; txb0_wr <= 1'b1; end
                    ADDR_TXB0D6: begin txb0_data[55:48] <= wdata; txb0_wr <= 1'b1; end
                    ADDR_TXB0D7: begin txb0_data[63:56] <= wdata; txb0_wr <= 1'b1; end

                    // Filter/mask registers and unsupported configuration registers
                    // are intentionally not writable in this reduced design.
                    default: ;
                endcase
            end

            // TXREQ state storage. Clear is processed before set so a new RTS in
            // the same cycle as completion/abort creates a fresh pending request.
            if (txreq_clear)
                txb0_txreq <= 1'b0;
            if (txreq_set)
                txb0_txreq <= 1'b1;

            // Dedicated hardware-clear events from Control Logic.
            if (clear_rx0if)
                canintf[0] <= 1'b0;
            if (clear_tx0if)
                canintf[2] <= 1'b0;
            if (clear_merrf)
                canintf[7] <= 1'b0;

            // Hardware SET has final priority so an event cannot be lost when a
            // host clear and a new event happen on the same clock.
            if (set_rx0if)
                canintf[0] <= 1'b1;
            if (set_tx0if)
                canintf[2] <= 1'b1;
            if (set_errif)
                canintf[5] <= 1'b1;
            if (set_merrf)
                canintf[7] <= 1'b1;
        end
    end

    // -------------------------------------------------------------------------
    // Register read multiplexer
    // -------------------------------------------------------------------------
    always @(*) begin
        case (addr)
            ADDR_BFPCTRL:  rdata = bfpctrl;
            ADDR_CANSTAT:  rdata = {opmod, 1'b0, icod, 1'b0};
            ADDR_CANCTRL:  rdata = canctrl;
            ADDR_TEC:      rdata = tec_reg;
            ADDR_REC:      rdata = rec_reg;
            ADDR_CANINTE:  rdata = caninte;
            ADDR_CANINTF:  rdata = canintf;

            ADDR_TXB0CTRL: rdata = {4'b0000, txb0_txreq, 3'b000};
            ADDR_TXB0SIDH: rdata = txb0_id[10:3];
            ADDR_TXB0SIDL: rdata = {txb0_id[2:0], 5'b00000};
            ADDR_TXB0DLC:  rdata = {1'b0, txb0_rtr, 2'b00, txb0_dlc};
            ADDR_TXB0D0:   rdata = txb0_data[7:0];
            ADDR_TXB0D1:   rdata = txb0_data[15:8];
            ADDR_TXB0D2:   rdata = txb0_data[23:16];
            ADDR_TXB0D3:   rdata = txb0_data[31:24];
            ADDR_TXB0D4:   rdata = txb0_data[39:32];
            ADDR_TXB0D5:   rdata = txb0_data[47:40];
            ADDR_TXB0D6:   rdata = txb0_data[55:48];
            ADDR_TXB0D7:   rdata = txb0_data[63:56];

            ADDR_RXB0CTRL: rdata = 8'h00;
            ADDR_RXB0SIDH: rdata = rxb0_id[10:3];
            ADDR_RXB0SIDL: rdata = {rxb0_id[2:0], 5'b00000};
            ADDR_RXB0DLC:  rdata = {1'b0, rxb0_rtr, 2'b00, rxb0_dlc};
            ADDR_RXB0D0:   rdata = rxb0_data[7:0];
            ADDR_RXB0D1:   rdata = rxb0_data[15:8];
            ADDR_RXB0D2:   rdata = rxb0_data[23:16];
            ADDR_RXB0D3:   rdata = rxb0_data[31:24];
            ADDR_RXB0D4:   rdata = rxb0_data[39:32];
            ADDR_RXB0D5:   rdata = rxb0_data[47:40];
            ADDR_RXB0D6:   rdata = rxb0_data[55:48];
            ADDR_RXB0D7:   rdata = rxb0_data[63:56];

            // Hardcoded filter/mask values remain readable but immutable.
            ADDR_RXF0SIDH: rdata = rxf0_id[10:3];
            ADDR_RXF0SIDL: rdata = {rxf0_id[2:0], 5'b00000};
            ADDR_RXM0SIDH: rdata = rxm0_mask[10:3];
            ADDR_RXM0SIDL: rdata = {rxm0_mask[2:0], 5'b00000};

            default:       rdata = 8'h00;
        endcase
    end

endmodule
