`include "can_defs.vh"

module control_logic (
    input  wire        clk,
    input  wire        rst_n,

    // ============================================================
    // SPI / HOST COMMAND EVENTS
    // ============================================================

    // OP_RTS_TXB0
    input  wire        rts_pulse,

    // OP_RESET
    input  wire        reset_pulse,

    // READ RX BUFFER completed
    input  wire        rxbuf_done,

    // ============================================================
    // CURRENT REGISTER VALUES FROM REGISTER BANK
    // ============================================================

    input  wire [7:0]  canctrl,
    input  wire [7:0]  bfpctrl,
    input  wire [7:0]  caninte,
    input  wire [7:0]  canintf,
    input  wire        txreq,

    // ============================================================
    // PROTOCOL ENGINE STATUS
    // ============================================================

    // Successful transmission pulse
    input  wire        tx_done,

    // Transmission aborted/error pulse
    input  wire        tx_abort,

    // Receive success / accepted frame pulse
    input  wire        rx_success,

    // Current error counters from Protocol Engine
    input  wire [7:0]  eng_tec,
    input  wire [7:0]  eng_rec,

    // Current CAN error state
    input  wire        eng_err_passive,
    input  wire        eng_bus_off,

    // ============================================================
    // RECEIVE BUFFER STATUS
    // ============================================================

    // RX buffer contains a valid received message
    input  wire        rx_full,

    // Received frame was RTR
    input  wire        rx_rtr,

    // Standard/Extended indicator
    input  wire        rx_ide,

    // Acceptance-filter hit information
    input  wire [3:0]  rx_filter_hit,

    // ============================================================
    // HARDWARE EVENT STROBES TO REGISTER BANK
    // ============================================================

    // Software/hardware reset request
    output wire        control_reset,

    // TXREQ hardware control
    output wire        txreq_set,
    output wire        txreq_clear,

    // CANINTF hardware SET/CLEAR events
    output wire        set_rx0if,
    output wire        clear_rx0if,

    output wire        set_tx0if,
    output wire        clear_tx0if,

    output wire        set_merrf,
    output wire        clear_merrf,

    // Generic error interrupt indication
    output wire        set_errif,

    // ============================================================
    // PROTOCOL ENGINE REQUEST
    // ============================================================

    // One-cycle request generated by RTS
    output wire        tx_start,

    // ============================================================
    // STATUS OUTPUTS TO SPI
    // ============================================================

    output wire [7:0]  status_byte,
    output wire [7:0]  rxstatus_byte,

    // ============================================================
    // ERROR COUNTER / ERROR STATUS MIRRORS
    // ============================================================

    output wire [7:0]  tec,
    output wire [7:0]  rec,
    output wire [7:0]  eflg,

    // ============================================================
    // PHYSICAL INTERRUPT
    // ============================================================

    output wire        int_pin
);


    // ============================================================
    // REGISTER BIT DEFINITIONS
    // ============================================================

    localparam integer RX0IF = 0;
    localparam integer TX0IF = 2;
    localparam integer ERRIF = 5;
    localparam integer MERRF = 7;


    // ============================================================
    // 1. RESET
    // ============================================================

    assign control_reset = (~rst_n) | reset_pulse;


    // ============================================================
    // 2. TX REQUEST MANAGEMENT
    // ============================================================

    assign txreq_set =
            rts_pulse &&
            !eng_bus_off;

    assign tx_start =
            rts_pulse &&
            !eng_bus_off;

    assign txreq_clear = tx_done;


    // ============================================================
    // 3. TX INTERRUPT
    // ============================================================

    assign set_tx0if = tx_done;
    assign clear_tx0if = 1'b0;


    // ============================================================
    // 4. TX ERROR / MESSAGE ERROR
    // ============================================================

    assign set_merrf = tx_abort;
    assign set_errif = tx_abort;

    assign clear_merrf = 1'b0;


    // ============================================================
    // 5. RX INTERRUPT
    // ============================================================

    assign set_rx0if = rx_success;
    assign clear_rx0if = rxbuf_done;


    // ============================================================
    // 6. ERROR COUNTER MIRRORS
    // ============================================================

    assign tec = eng_tec;
    assign rec = eng_rec;


    // ============================================================
    // 7. ERROR FLAG STATUS
    // ============================================================

    assign eflg = {
        eng_bus_off,
        eng_err_passive,
        6'b000000
    };


    // ============================================================
    // 8. READ STATUS
    // ============================================================

    assign status_byte = {
        canintf[RX0IF],
        1'b0,
        txreq,
        canintf[TX0IF],
        1'b0,
        1'b0,
        1'b0,
        1'b0
    };


    // ============================================================
    // 9. RX STATUS
    // ============================================================

    assign rxstatus_byte = {
        canintf[RX0IF],
        rx_full,
        rx_rtr,
        rx_ide,
        rx_filter_hit
    };


    // ============================================================
    // 10. INTERRUPT PIN
    // ============================================================

    assign int_pin = ~|(canintf & caninte);


endmodule